export const FETCH_RESPONSE = "FETCH_RESPONSE";
export const FETCH_USER_PHOTO = "FETCH_USER_PHOTO";
export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";
export const FETCH_ERROR_NEWS_FEED = "FETCH_ERROR_NEWS_FEED";
export const FETCH_ERROR_DURING_PHOTO = "FETCH_ERROR_DURING_PHOTO";
export const FETCH_ERROR_DURING_PROFILE = "FETCH_ERROR_DURING_PROFILE";
export const CLEAR_USER_PHOTO = "CLEAR_USER_PHOTO";
